[tools]
go = "1.25"
golangci-lint = "2.8.0"
just = "latest"
buf = "latest"
goreleaser = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
